### ISSUE TITLE
Elegoo Neptune 2

### ISSUE THREAD

**Issue by DirkTas67** [Toylerrr/ElegooNeptune2Integration#1]
Hello,

Just bought this printer and it arrived today, I wanted to add it to my Ubuntu system with the integration your made, it works fine but there is a strange thing. According to the Elegoon Neptune 2 user manual the build volume of the printer is 220x220x250 and when i look at the machine setings from your integration I see 235x235x260?

Regards,
Dirk

**Comment by Toylerrr** [comment]
Great question! 
The smaller size is what is advertised by Elegoo the bigger size is what is actually available for the printer. The reason why they say it's 220 x 220 so that you can always have a skirt around your 3D prints to purge the nozzle. 

The printer profile in this GitHub is pulled straight from Elegoos version of Cura and made easier to install in the typical version.
